In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("flipkart_sales.csv")

In [5]:
df.head()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1

In [7]:
df['Price (INR)'] = df['Price (INR)'].astype(int)
df['Total Sales (INR)'] = df['Total Sales (INR)'].astype(int)

In [9]:
df.head()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069,2,98139,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755,4,51023,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092,4,44368,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657,1,32657,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590,3,79770,2024-12-27,UPI,3.1